package lexico;

public enum TipoToken {
	OPMAIOR, OPMENOR, OPIGUAL,OPMENORIGUAL,
	OPMAIORIGUAL, IDTIPO, IDVAR, EOF, ERRO, OPAND, OPOR, OPSUM, OPSUB, OPMULT, OPDIV, OPMOD, CMDIF, CMDWHILE, CMDATR, VALBOOL, VALNUM, VAL_CHAR, VALFLOAT, PALAVRA_CHAVE, IDCONTANTE, COMENT_CLOSE, COMENT_OPEN, SIMBOLO, OPNEGACAO, IDTERMINADOR;
}
